# Generated by Django 4.2.15 on 2024-08-17 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserPhoneLabelMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, null=True)),
                ('fullname', models.CharField(max_length=100)),
                ('phonenumber', models.CharField(max_length=15)),
                ('label', models.CharField(choices=[('SPAM', 'SPAM'), ('SALES', 'SALES'), ('FRAUD', 'FRAUD'), ('VERIFIED', 'VERIFIED')], max_length=50)),
            ],
        ),
    ]
